name: Shell Scripts Unit Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install edirect
      run:  |
        sudo apt-get install -y ncbi-entrez-direct bats
        which esearch
    - name: test env
      run:  |
        echo $PATH
        which esearch
        which elink
        which efetch
        which xtract
        which bats
    - name: unit tests
      run:  for unittest in test/*.sh; do bats $unittest; if [ $? -gt 0 ]; then exit 1; fi; done;

