name: Shell Scripts Unit Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install edirect
      run:  |
        yes | bash lib/edirect/setup.sh
        source $HOME/.bash_profile
    - name: test env
      run:  |
        source $HOME/.bash_profile
        echo $PATH
        which esearch
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"

