name: Shell Scripts Unit Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install edirect
      run:  |
        sudo apt-get install -y ncbi-entrez-direct
        which esearch
    - name: test env
      run:  |
        export PATH=$PATH:$GITHUB_WORKSPACE/lib:$GITHUB_WORKSPACE/lib/edirect
        echo $PATH
        which esearch
        which elink
        which efetch
        which xtract
        which bats

